# This file was generated by GoReleaser. DO NOT EDIT.
cask "surge" do
  name "surge"
  desc "Surge is a blazing fast, open-source terminal (TUI) download manager built in Go."
  homepage "https://github.com/surge-downloader/surge"
  version "0.3.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "surge"

  on_macos do
    on_intel do
      url "https://github.com/surge-downloader/surge/releases/download/v#{version}/surge_#{version}_darwin_amd64.tar.gz"
      sha256 "149b78d47eb0192e195baa998006c1474b8eeeb596759d1e762f9b8220d12b9c"
    end
    on_arm do
      url "https://github.com/surge-downloader/surge/releases/download/v#{version}/surge_#{version}_darwin_arm64.tar.gz"
      sha256 "da44b78ff1ab169b6ee9f7591b3dc5a39a98d92fdcf219867462aa925b0b608b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/surge-downloader/surge/releases/download/v#{version}/surge_#{version}_linux_amd64.tar.gz"
      sha256 "d3efb24cac79056322a5572430490f957f269f6229d463e11818c5358c9fc8f1"
    end
    on_arm do
      url "https://github.com/surge-downloader/surge/releases/download/v#{version}/surge_#{version}_linux_arm64.tar.gz"
      sha256 "4b5b673a56a2ba92c811716e64b59eabbd44b0169b33d456ea23d53d1ae2d6e2"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/surge"]
    end
  end

  # No zap stanza required
end
