# This file was generated by GoReleaser. DO NOT EDIT.
cask "surge" do
  name "surge"
  desc "Surge is a blazing fast, open-source terminal (TUI) download manager built in Go."
  homepage "https://github.com/surge-downloader/surge"
  version "0.5.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "surge"

  on_macos do
    on_intel do
      url "https://github.com/surge-downloader/surge/releases/download/v#{version}/surge_#{version}_darwin_amd64.tar.gz"
      sha256 "3f5dc3b14e34b7149cd61b1323f308651247bed32f408b13910c00040ca530fc"
    end
    on_arm do
      url "https://github.com/surge-downloader/surge/releases/download/v#{version}/surge_#{version}_darwin_arm64.tar.gz"
      sha256 "ce319d1371fed5b7763b714a4f0817c4d657faa142bf3c3cf73cb8cd57998475"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/surge-downloader/surge/releases/download/v#{version}/surge_#{version}_linux_amd64.tar.gz"
      sha256 "3988ca2279b0fdb18a8b780380a67224f96866ec718ef3793081f6dfd0f0a5b1"
    end
    on_arm do
      url "https://github.com/surge-downloader/surge/releases/download/v#{version}/surge_#{version}_linux_arm64.tar.gz"
      sha256 "6e88da354406dd74a3bb5f7559b8fb834b5dfef28d2b6a861143a4e7c3e2a8dd"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/surge"]
    end
  end

  # No zap stanza required
end
