# This file was generated by GoReleaser. DO NOT EDIT.
cask "surge" do
  name "surge"
  desc "Blazing fast TUI download manager built in Go for power users"
  homepage "https://github.com/surge-downloader/surge"
  version "0.7.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "surge"

  on_macos do
    on_intel do
      url "https://github.com/surge-downloader/Surge/releases/download/v#{version}/Surge_#{version}_darwin_amd64.tar.gz"
      sha256 "dfa03f69d1c780c16111e97e140ab401e41c37bd12556df00460c3b56210f430"
    end
    on_arm do
      url "https://github.com/surge-downloader/Surge/releases/download/v#{version}/Surge_#{version}_darwin_arm64.tar.gz"
      sha256 "6169534ae38426eac335d06411bc7172000680295330bbe645d332c6945958af"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/surge-downloader/Surge/releases/download/v#{version}/Surge_#{version}_linux_amd64.tar.gz"
      sha256 "2f83c125b254181956eac03a90999d4f2263e50d2e2e54b0941b189d6ce8abb8"
    end
    on_arm do
      url "https://github.com/surge-downloader/Surge/releases/download/v#{version}/Surge_#{version}_linux_arm64.tar.gz"
      sha256 "a2cf42e0e68bce16e3d82967d51526f353c230bad770cf9e383d2dc5ba7d870e"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/surge"]
    end
  end

  # No zap stanza required
end
